version: '3.4'

services:
  users.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5031:80

  transactions.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5021:80

  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5011:80

  orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80